### ISSUE TITLE
Middle ground for Object.keys() using a generic type

### ISSUE THREAD

**Issue by kearfy** [total-typescript/ts-reset#102]
I've read the notice in the README, though: I would not describe myself as a perfectionist when it comes to typescript, but could we make a middle ground for `Object.keys()` using a generic type?

```typescript
declare global {
  interface ObjectConstructor {
      // Still defaults to a array of strings, but with the option to pass the type of the object :D
      keys<T extends object = Record<string, unknown>>(obj: object): Array<keyof T>
  }
}

const demo = {
  a: 123,
  b: 456,
  c: 789
};

// Untyped
const keys = Object.keys(demo);
// Typed
const typed = Object.keys<typeof demo>(demo);
// Because this is just ugly:
const ugly = Object.keys(demo) as Array<keyof typeof T>;

// This now works :D
typed.map(a => demo[a]);
```

Oh, and I guess also for `Object.entries()`

**Comment by kearfy** [comment]
Sure. I'd argue that this is not lying as the argument passed should be the same as the type in the generic, but then again a dev could lie to himself by not doing that I guess 🤷‍♂️

Just checking: Would it be valid though if you could enforce the type of the passed object, whilst still making it optional? I guess you could add a .typedKeys but that would nog really be a "reset" anymore

**Comment by mattpocock** [comment]
Yep, not interested in adding new methods.

> Would it be valid though if you could enforce the type of the passed object

You can't enforce the type of the passed object.
