### ISSUE TITLE
Type predicate in `ReadonlyArray.prototype.includes` may be incorrect

### ISSUE THREAD

**Issue by mefechoel** [total-typescript/ts-reset#103]
Hey there and thanks for this great library, I love the idea of a TS-reset. I think I've encountered some incorrect behaviour though.

This is also mentioned in #49 I believe, but since that issue is mainly about something else, I'm opening this new one.

The problem with the type predicate in `ReadonlyArray.prototype.includes` is that if it returns `true`, you know for sure, that the argument is of the same type as the array items. This does not work the other way round though. Just because the argument is not in the array, it does not necessarily mean that it is not of the same type as the array items.

The simplest (very contrieved) example I could think of is the following:

There are two union types. One of which is a subset of the other. If we have an empty `ReadonlyArray` of the subset type, and we check if it includes an element of the superset type, we know that the check will be come back as false. If we have an if/else branch for that case, TS will narrow the item we checked with `.includes` to the difference of the superset type and the subset type, which may not be true, as the item could well be of the subset type as well, it would just not be in the list.

In code it could something like this:

```ts
// Our superset type
type Code = 0 | 1 | 2;
// Our subset type
type SpecificCode = 0 | 1;
// Get a superset item that is also in the subset
const getCode = (): Code => 0;
const currentCode = getCode();
// Create an empty list of subset type
const specificCodeList: ReadonlyArray<SpecificCode> = [];

if (specificCodeList.includes(currentCode)) { // This will be false, since 0 is not in []
	currentCode; // -> SpecificCode
} else { // This branch will be entered, and ts will think z is 2, when it is actually 0
	currentCode; // -> 2
}
```

I've also created a more [real-worldy example](https://www.typescriptlang.org/play?ts=4.9.5#code/C4TwDgpgBA6glgEwgOwDJ2BATgQwDYA8AKgHxQC8URUEAHpsggM5RPBZzIDmAUFP1AD8rdp14CoALio16KZlGQBXALYAjbHwHDl6zROnU6DBWoD2ZvBBzIt-YecvXbBmcfks1cLp2B2hUF4+yH6uRnKMLEwg6pb+wtGxeP6GANw8PL7YAGY4AMbQAErWCGbIeCAAgli4IMRkAN5anHl4SkhMABT+TNZYeQAWAKJWKijAhlAAPlCd8EhoGNj49VAAZFANAL4AlAA0-tlYZioAkox0gtK6GlgH-DvSvTj9w6PjUHAsROlbGQD0-ygAAUsBATFBgAMvp8WPg8JCBtA8DYuFA8mYOlAzEosKwQGwICooABrZBmADuTB4oEgUFQqIAwpjoJQAEQoAC0AFUAMps6ZQDnITkAcQAQgKZmykJyACJDKVC2WVIhKtlHTkAMUK6s14sV6UBUAA8uUQIjoCozGxsdkGFAlL0EFAUdwlDguBAWBS4HgERp0fkkS7smY8UwTtAwThI7ZadBGcGcGorAzuMykBQhVy+equRK2ekeMaYBAAORgqBcMxiSFmKADGwIKxQMEARyU3uAcMYbfBuOQUBw-aYYDKvUROGAsNYUYGlNdZjy+DgAC8IAgS0DgA2odA2ZU8gUwMBOemuB6vQKkTgkFgaeAihBO92ABIlbAsShNACQh+PCBT3PVErwgNlpAvTMIF+DIMWQW03S4JNBggaQGigABtABpT4hxQptUwgKCWQAXSuR1kDJSkhy2bNtmLbIlGQPJgDgMpq3BAjNwvLodk2Hhf2NYo72Hf0g1Ql0kKYAA6KBTmyKAKQrKtSjrKEYTDPF9ygbI4CwW02LGKgkUE40V1QpS-QDaAiVPEA5N5FpoB0izoW4WdI2Msw1CYPJcRc9y0WUqBSmQcs-CEoEKRsGdd0CK1vWdKyoV045iRxHtEGgEKwWAQdhygESwoqapakEvKCpNNQACsIFYmSSQgAlOiQ7j+NjIqSjKUqahwOoCJTNMmRZEhYJ4JiWLYjimAXJQ8AQcUIG4hBWtRSCRqQR5XVRWdBqIkisz-SqsCHJCKHIdkC0laYZnOy6rpFPNxsm1j2LOsw71QZd8AgOVpxwNbuA2jMWW25jqIpIc-2Nb7RJ0vAftbZslI4TBPjivckQk7HwznMYNO4GTiYqgdTsUea8Be5i3o4ptGCsYpXzYToOy7Nh0MbT8DOkJn2eAD87y-KBdgE394MQ3bKDZ7sZNve8mEwgCTzPC8wLZUj0nFicZzcnjUW-TjgBW3jOh2LXjUZJE8hJT5FIR3aYT1hA5IUxQzBnZTy3E5AIE3esl3h7HEZXVsNC06AwGOAoEDEQS4EUzpnd4mSWjaDoga4HZ+L-KL5Pt6EWBhdgu2HPsQrdF1OERGE1FwFiBj2JToEh3S8aYAKp0ivPzphCAMCRPFhR5flsSH662UE39zuNTkyH24bQaQQS6IgPBJ1z0skSHDBZ3JGdq4Rr4ZwXZSADdsCbkKV3CmdAw7qsoWnHaPK+KfjQAKgAORNIgP5zJ6o88bD0LFfaANUnQzkhk3J+B8T6dX3glFAOMXQgHBDJd+QJeRYxck+KgvI8LZGFlpF+aJD6F0CPXQYe8PbonDGCBq8kZyzRxAtTBw5WIen9BaQMh0IBTxnkCOeyoIDykVIKGUojVR6iwNqXUEj9SKingnWYLD5qLWWsGTcmds5i1-HnIgFC1ELXdjObAxw7jDhYOdDE6i8K6XyHfaAZh7Z4IXsRTa-D9HTyZFozCSFSLZkRl9JGf0AY6K1r+P4USeB-G3FAN8zZkb9mZjOJ0dYRx1wwF8AYS5Q4QEcs5ABYobowljB3MYLo1AWhxBGAkmAVDxPioGEcGIVDWg+vkpuu8YRlGcQXaAbkhrIlCbJWA29LT4kJMSCBto2AvEwFuY0WBmLIHUtjPWnk2LiTsqAREOIuADB4PTFsEA+bdk6H+eWX50JT2VkBVWoFPTgWkCAyUBwokHF2OkIAA) in the ts playground using language codes and http request semantics to get closer to an actual use case.

I share your opinion from https://github.com/total-typescript/ts-reset/issues/49#issuecomment-1446014711 about `ReadonlyArrays` mostly being used in an exhaustive way, including all members of a union type, but that is not gererally true. I guess that if you'd encounter such an edge case we're this problem occurres it would be very hard to understand what's going on. That's why I would be more comfortable with a few more manual checks and `ReadonlyArray.prototype.includes` not being a type predicate unless there actually is a way of having it only be a type predicate if the result is truthy (that would be amazing!). Another option would be to remove this version from the recommended set of resets and having it as an opt in improvement. The base version without the type predicate could still be in the recommended resets and be overridden with the current implementation with a second import of this more altered version.

**Comment by mattpocock** [comment]
Yes, I think I agree with you. This was initially raised on Twitter in relation to normal arrays, but I think the same behaviour applies here.

I think we should probably revert the type predicate behaviour here.
