### ISSUE TITLE
Accept Generic Parameters for FormData, Response and Request

### ISSUE THREAD

**Issue by karlhorky** [total-typescript/ts-reset#11]
Hey @mattpocock 👋 Hope you're well!

Looks like a cool project! 👀

Wonder if you'd be open for enabling some DX improvements such as enabling `FormData`, `Response` and `Request` to take generic type parameters.

These have been requested in TypeScript itself, but it seems like the requests won't be implemented:

- https://github.com/microsoft/TypeScript/issues/43797
- https://github.com/microsoft/TypeScript/issues/52777

### `FormData`

```ts
type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

type Options<Method> = {
  method?: Method;
}

export async function fetchApi<Path extends string, Method extends HttpMethod>(
  path: Path,
  options: Options<Method> & {
    formData: `${Method} ${Path}` extends `POST /exercise-checks`
      ? { id: string, file: File } // 👈 Could be FormData<{ id: string, file: File }>
      : `${Method} ${Path}` extends `PUT /exercise-checks/${number}`
      ? { file: File } // 👈 Could be FormData<{ file: File }>
      : never
  }): Promise<
    `${Method} ${Path}` extends `POST /exercise-checks`
      ? { id: string } | { errors: string[] }
      : `${Method} ${Path}` extends `PUT /exercise-checks/${number}`
      ? { id: string } | { errors: string[] }
      : never
  > {
  return '' as any;
}

const file = new File([''], '');
const goodFormData = { id: '1', file: file }; // 👈 Could be new FormData() + .append
const badFormData = { incorrectProperty: false }; // 👈 Could be new FormData() + .append

// ✅ No errors
await fetchApi('/exercise-checks', { method: 'POST', formData: goodFormData })
// ✅ No errors
await fetchApi('/exercise-checks/1', { method: 'PUT', formData: { file: file } })
// ✅ Errors, incorrect method
await fetchApi('/exercise-checks/1', { method: 'PUTzzzzz', formData: { file: file } })
// ✅ Error, incorrect path
await fetchApi('/xxxxx', { method: 'PUT', formData: { file: file } })
// ✅ Error, incorrect form data
await fetchApi('/exercise-checks/1', { method: 'POST', formData: badFormData })
```

[TypeScript Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAEsxgLIWACwPYBMoF4oHIBxAUQBV8oAfAgBQHkBlcq2gVWevwBFiAZM4vgDcAKBGhIUOmGABLdADsAzgB5kaLAD5cUAN4ioUALYoMmAPwAuKOrOiAvmIgAPMOgBOwKAEMlIBQDGUABmAK6BcoohKAGoAIJgsio03mhQLsAQCphKUErA7rIKAOYANDamWOnOmdm5cAi2WgAUBlBgqajWKWilbegy8srW0pHKapWY2gBkem2GwR5GXKne1gAGACS6TZj2UNs9qPbr1bU5UOv0TFAA9C4Q7gGyShAAtLEQAQDWSuvzhig5j0UFkmGs+UKJXKwVkABsINYAGLw6D7W63KCAXg3ABI7UAAwuhQnDsAAjaBIpYrYDeFS6UHgvIFIplEKo5GoqD2TQAwwbba7faHTonM5ZC5Xdh3B5PF7vT4-JS3bYKUJGcnuE68oEg2EIjkIrl3TG4glEklQclQSnuZarOls-XWznc7XWBQQABujza9gAlN13OgjHKVACtjtJkLdEdRRlxbkroxSNLnI9nq8Pqgvr9-oDAcD6WCIcySkbqPTHkH3EoS1DigBtAC6XLdlwFUYOMZFp3jdUuNCl9zTsszCt+yt0qvVjy1+cMhYZdZZ5ZBVY8taZ9ebrfnUHdXp9hm0+kM7hQoXcCgIFF8PgUIAcYgCinyjugeA9AHdnQjmg38HwJtykAv1RBfZQvGKdAsBtO0aR0ItGXwABGfAYXZd8uSEY1sTxQliTJaBv2tKlVmaP0oAAaigAA6bwwEgbIRAgt9SW8TA4OpbxENBQIPHPAJgBoINIE8EBrGCbw4VebDcNNAiLStEiuPIyiaPoxjxTEDEoEAUHIoAAOXQdJ3GrJQRG8L9vFkLxghieJEmafBh3TOUsxzJR0JBEwNGQ65yBhMiaWsaDYOCnj-REXSDOM0zzMs6zbOiYBYgSWRnNc0d5WzRVbjQ8p6V8sxrHwQdApCCLrHpPVESw-YopiqBiDMjdyiKF8zK+LxiqwRKbLshz0symUMxyzz8u8orJlK8qAC8FoW7zFltbjqvfSSXS5P1osxAyWurdr+K6oT2k6frkvs1LHIylznHu+6puMGa2Aqlb4LWXVMNqo1Gr25rWvcI7OsEuyligTBVguwbruGlzRvc8clQKnyXrK5Nlqqy0ONUhCoqAA)

### `Response` and `Request`

Before:

```ts
export async function POST(request: Request): Response {
  const body = await request.json();
     // ^? const body: any ❌
  return new Response(JSON.stringify({
    abc: 123, // ❌ POST function return type cannot check type of response body object
  }))
}
```

After:

```ts
type RequestBody = { zzz: number };
type ResponseBody = { abc: number };

export async function POST(request: Request<RequestBody>): Response<ResponseBody> {
  const body = await request.json();
     // ^? const body: { zzz: number } ✅
  return new Response(JSON.stringify({
    abc: 123, // ✅ type checked
  }))
}
```

#### Caveats

1. Arguably, the `Request` body is unknown until runtime, so this is better handled instead with Zod or some other runtime validation. But for quick/simple projects without this validation, it's nice to be able to type the request body type.

**Comment by mattpocock** [comment]
Hey! I think I'd prefer not to add generics to Request, Response etc. The main reason is that I want to err towards correctness, not usability. When you call `Response.json()`, you truly don't know what you're going to get.

**Comment by karlhorky** [comment]
Ok, there are 3 points here:

1. `FormData` - enabling checking of the shape of data inside an instance of `FormData`
2. `Request` - arguably, validation should be done with [Zod](https://zod.dev/) or similar, as you mention
3. `Response` - this is for type checking responses returned from functions in a statically-analyzable way (eg. checking return values of API handlers) - also mentioned this [here](https://github.com/microsoft/TypeScript/issues/52777#issuecomment-1437091953)

So I think your comment above only relates to point 2.

I think the highest value is probably the `Response` generic parameters. The [`Response` type from `@types/express`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/be74f7ba952fdd657cfddd883069383b72491671/types/express/index.d.ts#L128-L131) has prevented a lot of bugs from happening in our applications.

But maybe this is not the focus of the `@total-typescript/ts-reset` library.

**Comment by darcyrush** [comment]
@karlhorky I wonder if you (or even @mattpocock ) with your typing knowledge can help with a tangential question which is out of scope of the `ts-reset` library;

In [@types/express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/be74f7ba952fdd657cfddd883069383b72491671/types/express/index.d.ts#L128-L131) both the `ResBody` and `ReqBody` types default as `any`
```ts
interface Request<
      P = core.ParamsDictionary,
      ResBody = any,
      ReqBody = any,
      ReqQuery = core.Query,
      Locals extends Record<string, any> = Record<string, any>
  > extends core.Request<P, ResBody, ReqBody, ReqQuery, Locals> {}
```
How would you use declaration merging to change these to `unknown` instead? 

I have tried variations of the following, which can augment properties but not override;
```ts
declare global {
  namespace Express {
    interface Request extends Record<string, unknown> {
      addition: "a" | "b"; // Augments ok
      body: unknown; // Remains any
    }
  }
}
```
