### ISSUE TITLE
Allow functional components to return `React.ReactNode`

### ISSUE THREAD

**Issue by kevinbarabash** [total-typescript/ts-reset#115]
I was able to fix this locally by editing the index.d.ts for `@types/react`.  I changed:
```
interface Element extends React.ReactElement<any, any> { }
```
to 
```
type Element = React.ReactNode;
```
inside of the `JSX` namespace.

**Comment by jacobofbrooklyn** [comment]
You should comment this on [this new video](https://www.youtube.com/watch?v=M3TPmOpNFCs) from Matt which might send the feedback to the React team to be actually added to React.

**Comment by mattpocock** [comment]
This causes MANY issues throughout global scope. interfaces should never be overridden by types.
