### ISSUE TITLE
Not working with svelte with ts

### ISSUE THREAD

**Issue by krishnaTORQUE** [total-typescript/ts-reset#119]
Not working with svelte + ts using vite with default settings.

**Comment by mattpocock** [comment]
Could you provide a reproduction?

**Comment by krishnaTORQUE** [comment]
> npm create vite
> Select Svelte + TS

add this npm module & test

its not working with default configs

**Comment by mattpocock** [comment]
I assume you're also adding the `reset.d.ts` file?

**Comment by krishnaTORQUE** [comment]
No I dont

**Comment by mattpocock** [comment]
OK, check the installation instructions and I'll reopen if needed.
