### ISSUE TITLE
Bug - most recent version does not have dist folder published

### ISSUE THREAD

**Issue by BenLorantfy** [total-typescript/ts-reset#13]
I noticed version `0.3.3` does not have the `dist` folder published:

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/4398635/220153692-274fa7d0-72aa-4a03-bc87-85d12abef066.png">

So none of the typings are being reset when I try the latest version

https://www.npmjs.com/package/@total-typescript/ts-reset/v/0.3.3?activeTab=explore

**Comment by mattpocock** [comment]
Thanks! My bad. CI is deploying a fix now.
