### ISSUE TITLE
after filter(Boolean) .map is still concerned about undefined values

### ISSUE THREAD

**Issue by baronyoung** [total-typescript/ts-reset#134]
`                    id={week.filter(Boolean).map((day) => day.date)).join(",")}
`
"week" is (Day|undefined)[]
On the "...day.date..." , I get a lint error saying "day could be undefined".  Is this expected?  I installed per instructions for all rules.

**Comment by mattpocock** [comment]
Could you provide a repro?

**Comment by baronyoung** [comment]
Here's one without ts-reset installed.  If you could point me to a repo that would let me install a package I can add it there.

https://www.typescriptlang.org/play?ts=4.9.5#code/JYOwLgpgTgZghgYwgAgCJwJ7IN4ChnIAmckAXGiRLgL64A2EYyAznALYAOD6GpPyAXhzEyICAHcKkABQBKWgybiIEANblpPAD4BXEIQgxQEQrIDaAXUHIzeg0bGEANC3ZcIPC7nqNkAD2tlNQA6IzpIKGkAIQB7GIY4EFlgtjgOaWIsAQA+IkxgkQhZbyA

**Comment by nklisch** [comment]
I am seeing something similar

**Comment by baronyoung** [comment]
Ok here it is [https://codesandbox.io/s/distracted-hypatia-ypgn9h?file=/src/index.ts](url)

The code is in index.ts

**Comment by mattpocock** [comment]
Seems like an issue with codesandbox itself, works fine in a TS playground.

https://www.typescriptlang.org/play?#code/PTAEEkFsAcHsCcAuoCWA7UBDUBndBzAGwFNQAzFEgGlEQAtiNMBjeWHHUAT1gFd5QAdzqwSoaGwBWxZogB0CgFAoYCZACIAAoliJMhALSIu0YjlYpoiYIhwH4Z4onUBuRcrSJi8Mi1IARTC5QAG9FUFAAE0wvAC5QQK83AF93EmQcTBgSQK543NAAXlComOJ4tGJBBLKACgBKUGS3dKFiYgBrItAAbV40SOIKSsiaTOziXIBdN0VWgA9uwXaOuQpCL3hagCFYUWJMNHq5SExoWtrorkbCgD5Srjlor3q3IA

**Comment by baronyoung** [comment]
So sorry about that

**Comment by mattpocock** [comment]
No worries!
