### ISSUE TITLE
Improve `reportError`

### ISSUE THREAD

**Issue by devinrhode2** [total-typescript/ts-reset#137]
lib.dom [has](https://user-images.githubusercontent.com/539816/230931145-a2137eab-9495-42e9-b5a0-0350207c4386.png) this code:
```ts
declare function reportError(e: any): void;
```

This would be better:
```ts
/**
 * The `reportError()` global method may be used to report errors
 * to the console or global event handlers,
 * emulating an uncaught JavaScript exception.
 * 
 * https://developer.mozilla.org/en-US/docs/Web/API/reportError
 */
declare function reportError(e: Error): void;
```

mdn docs:
https://developer.mozilla.org/en-US/docs/Web/API/reportError

**Comment by qb20nh** [comment]
It is defined as `any` on the html spec
https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope-mixin
```webidl
interface mixin WindowOrWorkerGlobalScope {
  ...
  undefined reportError(any e);
  ...
};
```

**Comment by ArthurKa** [comment]
Seems not like TypeScript.

**Comment by mattpocock** [comment]
@qb20nh 

Thanks for the research, that makes enough sense to me that we should close this.

**Comment by devinrhode2** [comment]
This is marked completed but I'm curious what the final code is
