### ISSUE TITLE
Feature Request: `Boolean()` behaviour vs `!!` operator

### ISSUE THREAD

**Issue by hubastard** [total-typescript/ts-reset#138]
`Boolean()` constructor does not behave like the `!!` operator. Boolean is useful in react conditional rendering when checking for an optional string to avoid rendering issues.

When we use `!!` typescript understands that the value cannot be optional/falsy anymore.

For example:
```tsx
<>
  {!!label && <Text>{label.toUpperCase()}</Text>}
</>
```

But when you use `Boolean()` typescript still thinks that the value can be optional/falsy. Which forces you to unwrap the value using `!` or add `?`.

For example:
```tsx
<>
  {Boolean(label) && <Text>{label!.toUpperCase()}</Text>}
  {Boolean(label) && <Text>{label?.toUpperCase()}</Text>}
</>
```

**Comment by kristian-puccio** [comment]
I'm trying to filter a readonly array and I'm seeing  this issue
```
Argument of type '<T>(ref: T | undefined) => boolean' is not assignable to parameter of type 'BooleanConstructor'.
  Type '<T>(ref: T | undefined) => boolean' provides no match for the signature 'new (value?: any): Boolean
```

If I comment out `  new (value?: any): Boolean;` from `BooleanConstructor` then the issue goes away.
