### ISSUE TITLE
Place “types” first in exports field

### ISSUE THREAD

**Issue by frehner** [total-typescript/ts-reset#15]
Thanks for this package!

I just wanted to bring up that the TypeScript team recommends that

> … the "types" condition should always come first in "exports".

https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing

**Comment by mattpocock** [comment]
I swear, `exports` is the bane of my life.

**Comment by frehner** [comment]
Haha, that’s a very common sentiment.

**Comment by mattpocock** [comment]
Fixed
