### ISSUE TITLE
Unable to import certain rules

### ISSUE THREAD

**Issue by chanp-ark** [total-typescript/ts-reset#156]
I want to import all the rules except the `json` rule. Doing so triggers a lint error: 
- `ESLint: Unable to resolve path to module '@total-typescript/ts-reset/array-includes'.(import/no-unresolved)`

In `package.json`, I have:
```
"dependencies": {
    "@total-typescript/ts-reset": "0.4.2"
}
```

In `src/reset.d.ts`: I have
```
import '@total-typescript/ts-reset/array-includes';
import '@total-typescript/ts-reset/array-index-of';
import '@total-typescript/ts-reset/filter-boolean';
import '@total-typescript/ts-reset/is-array';
import '@total-typescript/ts-reset/map-has';
import '@total-typescript/ts-reset/set-has';
import '@total-typescript/ts-reset/utils';
```

In case this was just a lint issue, I checked how filter would do:
![Screenshot 2023-07-25 at 5 16 45 PM](https://github.com/total-typescript/ts-reset/assets/56608740/3aa770b3-73dc-4946-af74-9e0c2341bfe9)

I also tried installing those specific rules in the `package.json` without success.

**Comment by Villae** [comment]
I had same problem and adding /dist part of the path fixed it:
``` js
import '@total-typescript/ts-reset/dist/fetch';
```

**Comment by chanp-ark** [comment]
@mattpocock can we update the docs to have `dist` in the path?

**Comment by ArthurKa** [comment]
@chanp-ark, what VS Code extension do you use to see type declarations inline?

**Comment by mattpocock** [comment]
@chanp-ark What `tsconfig` options do you have? Specifically, for `moduleResolution`?

**Comment by ReinisV** [comment]
happens for me too, importing whole package works fine, but if I want to use specific rules only, then adding `dist` is required.

my tsconfig.json:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "noImplicitAny": true, 
    "jsx": "preserve",
    "jsxFactory": "VueTsxSupport",
    "importHelpers": true,
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": false,
    "useDefineForClassFields": true,
    "sourceMap": true,
    "baseUrl": ".",
    "experimentalDecorators": true,
    "types": [
      "webpack-env",
      "jquery",
      "resize-observer-browser" 
    ],
    "paths": {
      // omitted for briefness
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules/*",
  ]
}
```

**Comment by chanp-ark** [comment]
> @chanp-ark What `tsconfig` options do you have? Specifically, for `moduleResolution`?

`"moduleResolution": "node",` is what I have! The following is the rest of my tsconfig. Thanks!

{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "DOM",
      "DOM.Iterable",
      "ESNext"
    ],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "next-env.d.ts",
    "i18next.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "cypress",
    "node_modules"
  ]
}

**Comment by mattpocock** [comment]
As it says in the docs, you need to have `moduleResolution: "nodenext"` or `moduleResolution: "node16"` to let you import ts-reset.

Could you try adding that?

**Comment by ArthurKa** [comment]
Or just import it in correct way like
```json
{
  "compilerOptions": {
    "types": [
      "webpack-env",
      "jquery",
      "resize-observer-browser",
      "@total-typescript/ts-reset/dist/fetch",
    ],
  },
}
```

**Comment by mattpocock** [comment]
@ArthurKa This is NOT recommended because if you specify one member of `types`, you need to specify all of them.

**Comment by tylerlaprade** [comment]
> As it says in the docs, you need to have `moduleResolution: "nodenext"` or `moduleResolution: "node16"` to let you import ts-reset.

@mattpocock, first, thank you for this amazing library! It's the most excited I've been about TypeScript in about a year.

I'm not sure which docs you are referring to here. Do you mean `ts-reset` or TypeScript itself?

A search in this repo only turns up Issues and Discussions, no docs.
<img width="461" alt="image" src="https://github.com/total-typescript/ts-reset/assets/5475199/b93a990b-9fa8-43d0-ba1d-385e3fb2217a">

A search on `totaltypescript.com/ts-reset` only turns up generic TypeScript tutorials, not `ts-reset` specific results.
<img width="855" alt="image" src="https://github.com/total-typescript/ts-reset/assets/5475199/d959ec4f-c226-4cfc-bd9a-b9a8ced72003">

**Comment by mattpocock** [comment]
@tylerlaprade The link to the docs is in the readme of this project.

**Comment by tylerlaprade** [comment]
Found it, thanks! I was looking at the docs, but it was not visually easy to distinguish that section, so I had been relying on the site's search functionality mentioned above.
