### ISSUE TITLE
`.filter` for a `PromiseSettledResult<T>` array from `Promise.allSettled`

### ISSUE THREAD

**Issue by Sheraff** [total-typescript/ts-reset#157]
Would it make sense to add some types for filtering the array result of a `Promise.allSettled`?
`const a: PromiseSettledResult<T> = Promise.allSettled([...])`
- `a.filter(r => r.status === 'fulfilled')` => `PromiseFulfilledResult<T>[]`
- `a.filter(r => r.status === 'rejected')` => `PromiseRejectedResult<T>[]`

**Comment by mattpocock** [comment]
Unfortunately not, due to the way that TS works here.
