### ISSUE TITLE
Type widening issue with `.filter(Boolean)`

### ISSUE THREAD

**Issue by tjk** [total-typescript/ts-reset#163]
Is this expected?

```typescript
type A = {
  a: string
}

const as1: A[] = [
  { a: "1" },
  { a: "2", b: false },
         // ^ Type '{ a: string; b: false; }' is not assignable to type 'A'.
         //     Object literal may only specify known properties, and 'b' does not exist in type 'A'.
]

const as2: A[] = [
  { a: "1" },
  { a: "2", b: false }, // no error
].filter(Boolean)
```

[TS Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEA7KBbEBnADlMCAqAygEoYgAu8A3gFDzxkCemCAcgPaIBiUE6DAPHgB88ALzw88EAA8yIRMHTwAZj3QIAPvAAM8LQCJ9epAFcIEYyYUhlAS0Qhgx7Ylp14AfiQgAbiBhudABcEgDc1AC+1NT2cjCquPAAgjAwUALCVG52EHEAFJhwwLZgUHIhAEJsbBAgUIgAwhzoZDAmYGRsMAA09AAWtugpAOYeIfUMAJQhhCTqZAB07FxqGUIA2gC64VExiHEJCCRQwBwQDClpa1l0OfmFjiVlIJXVtfVNiC1tHV29ZAMhjBRuNEFMZsRSItltxeGstjtorF-Idkjd4FAQt97MNItEwM0KFB0ABGEJJLZieDrNyUDEhfQkowRbq0+nwfQAJn0vQARiFVLwECzqJt8YSMehOeTKeIaXQ6ZiOUz4CKFeyuTz4PyVGphazNgs7v48lUanVEJNqEA)

**Comment by mattpocock** [comment]
Doesn't look like ts-reset is to blame here!

**Comment by tjk** [comment]
@mattpocock could you elaborate please?

**Comment by mattpocock** [comment]
Try it without ts-reset installed - same result.

**Comment by tjk** [comment]
But without ts-reset, the base .filter(Boolean) improvements also have same
result.... I'm asking why this could not also be improved? We can both see
it could do a better job here, right? Is this just not possible?

**Comment by mattpocock** [comment]
Right - no, it isn't, because of the way that TS treats excess property checking.
