### ISSUE TITLE
[docs site] small typo in docs site for `Map.has`

### ISSUE THREAD

**Issue by ekilah** [total-typescript/ts-reset#164]
(about https://www.totaltypescript.com/ts-reset)

small fix! the `[2, "waqas"]` member in these 2 code snippets should be `["waqas", 2]`, re: the supposed error message on the key mismatch:

```ts
// Argument of type '"bryan"' is not assignable to
// parameter of type '"matt" | "sofia" | "waqas"'.
```

<img width="831" alt="image" src="https://github.com/total-typescript/ts-reset/assets/3213339/67c2bbaf-3f5c-4ce6-aaa4-e9946c10c96e">

**Comment by mattpocock** [comment]
Fixed, thanks!
