### ISSUE TITLE
copyable npm install command in docs landing page

### ISSUE THREAD

**Issue by ReinisV** [total-typescript/ts-reset#165]
I knows its a weird ask, but can we make the npm install command on the landing page a text instead of an image?

I usually copy the install command from the docs to save a few seconds instead of retyping it and if its an image then:
![image](https://github.com/total-typescript/ts-reset/assets/10805335/87e1e8be-6e32-488d-adf8-25b4cec8a344)

**Comment by mattpocock** [comment]
It's just below it in the body text.

**Comment by ReinisV** [comment]
oh yeah, did not notice it. I guess the header image caught all of my attention there.
