### ISSUE TITLE
Importing specific rules doesn't work as documented

### ISSUE THREAD

**Issue by SuperKXT** [total-typescript/ts-reset#169]
The documentation says to import the rules directly like so:
```ts
import '@total-typescript/ts-reset/dom';
```

This however does not seem to work. I need to import it from the `dist` directory:
```ts
import '@total-typescript/ts-reset/dist/dom';
```

**Comment by mattpocock** [comment]
@SuperKXT What's your moduleResolution in tsconfig.json? It should be NodeNext or Bundler.

**Comment by SuperKXT** [comment]
Ah, right. I've been meaning to update the tsconfig file for this project. Thank you. 

Changing to `Bundler` breaks the types for `vite-plugin-eslint`, which is annoying.
