### ISSUE TITLE
Docs page is broken

### ISSUE THREAD

**Issue by russelldavis** [total-typescript/ts-reset#185]
The readme links to https://totaltypescript.com/ts-reset for docs. That page has some minimal content but is mostly blank (e.g., there's a "Get Started" section with no content). It looks like the actual docs are at https://www.totaltypescript.com/ts-reset-article

**Comment by mattpocock** [comment]
Looks fine to me!

<img width="710" alt="image" src="https://github.com/total-typescript/ts-reset/assets/28293365/0e398730-6b29-4f04-baa1-4b034aac4f9c">

Could you give me more steps to reproduce?

**Comment by russelldavis** [comment]
Weird. If I load it on my iphone, it works fine. If I load it on my macbook on chrome, safari, or firefox, I get this:

![www totaltypescript com_ts-reset](https://github.com/total-typescript/ts-reset/assets/551404/244e45c1-2697-44ca-8c8b-c0674638498f)

**Comment by russelldavis** [comment]
Inspecting the page, the content is all there, but all the invisible elements have `opacity:0` in the style tag.

**Comment by russelldavis** [comment]
Ok, I figured it out. It happens when [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is enabled. Probably an issue with the page's animation logic.

**Comment by vojtaholik** [comment]
Thanks y'all, this has been fixed.
