### ISSUE TITLE
Filter throws error when using `as const`

### ISSUE THREAD

**Issue by IanVS** [total-typescript/ts-reset#193]
I found a problem when using an object with readonly keys and accessing one of them dynamically.  It's tough to explain, so here's a minimal example:

```ts
const test = {
  A: [{ key: 1 }, { key: 2 }],
  B: [{ key: 3 }, { key: 4 }],
} as const;

function check(x: 'A' | 'B') {
  test[x].filter(y => y.key > 1)
}
```

Results in an error:

```
Argument of type '<T>(y: T | undefined) => boolean' is not assignable to parameter of type 'BooleanConstructor'.
  Type '<T>(y: T | undefined) => boolean' provides no match for the signature 'new (value?: any): Boolean'.
```

If I remove ts-reset, remove `as const`, or access `test.A` directly, there is no error.

**Comment by stychu** [comment]
I have the same problem with an const array of object. This is so annoying :(

**Comment by none23** [comment]
Reproduction: 
[TS Playground](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&declaration=false&pretty=true&isolatedModules=true&verbatimModuleSyntax=true&allowSyntheticDefaultImports=false&useUnknownInCatchVariables=true&ts=5.2.2&isolatedDeclarations=false#code/FAEwpgxgNghgTmABAOxgWzAZwA4wkgFQGUAlLMAF0QG9hFEKBPbJAOQHtkAxGKTRgDwEAfIgC8iAojAAPCmGQhMiAGa9MSAD6IADIm0AiA-pQBXKFBOnFYFQEtkYECZ3I69RAH4UYAG5g4d3oALkkAbmAAX2BgB3k4NXxEAEE4OBhBERp3eyh4gApsBBA7CBh5UIAhdnYoMBhkAGFOTAo4UwgKdjgAGgYACztMVIBzT1CGxgBKUOIyDQoAOg5udUzhAG0AXQjo2OR4xKQyGBBOKEZU9PXs+lyCoqdS8rAqmrqG5uRW9s7uvoog2GcDGE2Q01mpHISxWPD4622uxiwAgLSo8la4luKVCG2oiAA1mBGKEAIyISJ9fFEkmIABMFK2PXclVx1OJoQAzBSqYSOYgACyM5mRRAwZSo74UCLAFTWTp2TiICD9SAE-IyUI09gqBjMMA6hhYChTbEICimODII2tDYyLaLe4BfKMcSiRiLGmIUSkqZRYBAA)

**Comment by none23** [comment]
The fix seems pretty easy, I've opened a PR
