### ISSUE TITLE
Broken Documentation Site

### ISSUE THREAD

**Issue by liamlagezyxis** [total-typescript/ts-reset#199]
The 'Get Started' section in the [docs](https://www.totaltypescript.com/ts-reset) appears to be broken.

Environments Tested:
Microsoft Edge 126.0.2592.102 (Official build) (64-bit)
Google Chrome 126.0.6478.183 (Official Build) (64-bit)

Steps to reproduce:
Go to the [docs](https://www.totaltypescript.com/ts-reset)
Click on 'Get Started' or scroll to the section.
Note that it is empty.

Expected behavior:
The documentation should be populated.

Screenshot:
![image](https://github.com/user-attachments/assets/1f1a0c4e-027c-4f7c-a206-0307d0354e6e)

**Comment by danielo515** [comment]
I was going to report exactly the same. Not that it is broken, the info is there, but the styles do hide it
![Screenshot 2024-07-24 at 10 46 36](https://github.com/user-attachments/assets/0937bd20-2098-42e1-84c5-c1dafdfebdf4)

**Comment by MendyLanda** [comment]
same for me. 
it's been like this for a few months..

**Comment by vojtaholik** [comment]
Thanks y'all, this has been fixed.
