### ISSUE TITLE
Improve filter with type guards

### ISSUE THREAD

**Issue by Rawnly** [total-typescript/ts-reset#20]
I think the `filter` could be improved by using the following declaration:

```ts
interface Array<T> {
  find<S extends T>(
    predicate: (this: void, value: T, index: number, obj: T[]) => value is S,
    thisArg?: any
  ): S | undefined;
}
```

This allows to use `type-guards` as filters and get a well-typed return type ([playground link][playground])

#### Example Usage
```ts
const isNumber = (n: any): n is number => typeof n === 'number'
const arr = [1, 2, undefined, null, 'hello']

const numbers = arr.filter(isNumber)
//    ^? const numbers: number[]
```

[playground]: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgIJSnAngHgCoB8yA3gFDLIygAmOAyshAB6QjUDOyhAFORcgAcoEasARxIALmTcwAC2DtpANwD2wagBpkyuABsArhGl5tNZtJAGAtgCNo21bYBWJgNoBdAJTIAvEV1DFEVkOk0+CnlFdABzAH5pOBAsPi9pBgAfZAM2CCoQEQBuUgBfUnKwLAEUACUIBDA-Ej4AaxppAHJhBo7iigB3DXlLG3soPuQ5CGAYuTARu2gJpgWxiaxVpdKKqpQAYWAoBD0UX2aKNrZOhEPjiF6+TFEDJWQrRfG+FbfRrYoNn4fYolZA7aqhORwcFnA5HE7ILJ1BrlAD0ACo0eQ0aDkNjKuCYgY4FAOMgktRkAhVCB2GAoAYGqooOwsbiUaQqTTGnRIdDzshFEj5jJ2LzjBCoRA0shRZKBZwhX4iB1BtR5B0BSAZWLwhRFLC7tJuLLqukxdKTcFOAb4f5kF04M92BrQNrJbrKbcTkansAXpsoNo3ExtFgPNJgwHQwHvNIbaciNwyPxkJdqNcvfcPRRfS9s8gQ8gUhQSl4Pd1hdx+lHJjW3AXQ8gPMgI993mNo4CxrHkIq7UmIqn2vaKx186rhsh+vmpjM5tI5PnC1gcchSx72ABHInCI3sYAAL3F7YcyGDyEb4bPbd+gaLMelfaIg55koAdBXjYeINp90eg8u3jbKQKIosgAC0kFQdBkHIAAqnQqAAOIAKIQTBGGYeUnK0m61SvK+1SeE0bh8IREBvjccIQNwACsQYAEwAAzaAxtHeB65FvluO40cxQYscgTEcWRYofvUYDcAAHIJACMTGCW4sn0cgylAR4qJgf0KAgKo-TIDEECNAABrCehIJ4xmarSECOsgqgwMgxnkZZHLUrhVF3JwZyWuwb5UHokBQNwXH6pmXggWBKYAHpxJpaC6fI0CMEwcDWAI8JuVy8oAHK3k03AgIkyTSlqIQnlASrIPiEAOW8fi+GcHQVR0WW4YodB0qAMQFa8SRYBa8oyl1IA9XaNV1d5jX2rSUDda1OGNIoeUfAA8lAnVzaNBWBMVA0qPoQ0VQiw1bWNRDLbe3CBD4GRZB1I0xNd+gRW1jTEpVZxKax2g5NQeSgCI2hWHoejaB0Uyg6oHQaaBMVxW9XbQN5ZIYP5wCBdA3CXR8EVw-wsXYe5jSzd1KMfejmPBQ9Z141FFCE4j1jAEwIhNBTAVBdj7ArWM62bd1dPw0AA

**Comment by mattpocock** [comment]
This works without ts-reset!

**Comment by Rawnly** [comment]
got biased by a recent read 😅
