### ISSUE TITLE
Question: Can we define NonEmptyArray<T> in ts-reset library?

### ISSUE THREAD

**Issue by gerkim62** [total-typescript/ts-reset#200]
Is it possible for ts-reset to providea type that makes sure an array[0] can never be undefined even when     "noUncheckedIndexedAccess": true
is enabled in tsconfig?

**Comment by none23** [comment]
IMO, utility types like this are outside the scope of `ts-reset`.

You can define it youself 
```ts
type NonEmptyArray<T> = ReadonlyArray<T> & { 0: T }
```

**Comment by mattpocock** [comment]
Agree!
