### ISSUE TITLE
Feedback and suggestions

### ISSUE THREAD

**Issue by MaximeBernard** [total-typescript/ts-reset#26]
Thanks a lot for this. It makes a lot of sense while we wait for TS to "fix" those typings (and remove `any` from the language 🤪)

May I suggest 2 enhancements?

## Use `tsconfig.json` instead of `import`

Since it's global like `lib.dom.d.ts`, it makes more sense in the compiler options imho. 

## Separate `any-to-unknown` and `less-strict` rules  

I'm a bit confused about 
- `import "@total-typescript/ts-reset/array-includes";`
- `import "@total-typescript/ts-reset/set-has";`

Why would you want something less strict? Maybe you could give some examples to show why you would want that. I've been having scenarios with `Array.includes()` where sometimes it's nice to have `T | U` and sometimes it's easier with `string` but less "true".

Meanwhile, I would separate those sets of rules so your users could choose easily to pick `unknown-to-any` rules which make your code safer and not the other one.

**Comment by mattpocock** [comment]
Could you lodge these as two separate issues?

**Comment by MaximeBernard** [comment]
Done :)

- #30 
- #32
