### ISSUE TITLE
Separate any-to-unknown and less-strict rules

### ISSUE THREAD

**Issue by MaximeBernard** [total-typescript/ts-reset#32]
I think it would be good to have 2 separate sets of rules
- `any-to-unknown`
- `less-strict`

I'm a bit confused about
- `import "@total-typescript/ts-reset/array-includes";`
- `import "@total-typescript/ts-reset/set-has";`

Why would you want something less strict? Maybe you could give some examples to show why you would want that. I've been having scenarios with `Array.includes()` where sometimes it's nice to have `T | U` and sometimes it's easier with string but less "true".

Having separate sets of rules, it's easier to pick `unknown-to-any` rules which make your code safer and not the other one (which makes your code less true but improves DX).

**Comment by mattpocock** [comment]
I'd still like to keep array-includes and set-has in the recommended rule set, and I'm happy with the current workaround of only importing the rules you want.

If we add more configurations, we'll need to document and justify those configurations.

**Comment by MaximeBernard** [comment]
It won't scale if you plan to do dozens of rules.

Until then I'm fine with the current workaround 👍
