### ISSUE TITLE
Feature request - Smarter `Boolean`

### ISSUE THREAD

**Issue by Calvein** [total-typescript/ts-reset#35]
This is a great project 😍 

I add a suggestion to "patch" `Boolean` because I have been stumped by it at multiple occasions, e.g:

```ts
const fn = (arg: 'string' | null) => {
  const bar = Boolean(arg)
  if (bar) {
      return arg.toUpperCase()
          // ^? (parameter) arg: "string" | null
  }

  const baz = !!arg
  if (baz) {
      return arg.toUpperCase()
          // ^? (parameter) arg: "string"
  }

  return arg
}
```

And [the TS Playground link](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZmGBeGAKAhgJwOYC4YDk0mAlmNgTAD4xgCuANgwJTIB8MA3gFAwyiRYAIyzIYAIRAgGAU3RgMOZrxgk4aEZlY8+umJhlQ6mRFmwA6KCACqAB1szMAYXQQZqZXq8wA9D5gAegD8KgC+3CoC0DAiAF5iAIQJZipqGuix2ip6BkYmMGaWNvaOLm4e2d6+-sFhEXy5xqY43KFAA).

---

In real code examples, I usually have a combination of variables (e.g: `const hasData = Boolean(!isLoading && data && !hasError)`) and I found `Boolean` to be quite "dumb" compared to the less elegant `!!`. I don't know if it's normal and I'm missing something of if it could be patch like `Array#filter`.

**Comment by mattpocock** [comment]
I don't think it's possible to make it work how you describe in your above comment. I've had a good go, and I'd welcome someone reopening this issue if they do find a way.

The only way I got it to work is by doing `if (Boolean(somethingThatMightBeUndefined))` - in which case the Boolean call is redundant.
