### ISSUE TITLE
bug: Individual imports not working

### ISSUE THREAD

**Issue by petetnt** [total-typescript/ts-reset#36]
Hi Matt,

it seems that the individual entrypoints for the helpers are broken.

For example, considering the following:

```ts
import "@total-typescript/ts-reset/array-includes";
import "@total-typescript/ts-reset/fetch";

const users = ["matt", "sofia", "waqas"] as const;

const isUser = (input: string) => {
  if (users.includes(input)) {
    // input is narrowed to "matt" | "sofia" | "waqas"
    console.log(input);
  }
};

fetch("/")
  .then((res) => res.json())
  .then((json) => {
    console.log(json); // any
  });
```

Shows an error in `users.includes` and `console.log(json)` is still `any`.

However, including the whole library works just fine:

```ts
import "@total-typescript/ts-reset";

const users = ["matt", "sofia", "waqas"] as const;

const isUser = (input: string) => {
  if (users.includes(input)) {
    // input is narrowed to "matt" | "sofia" | "waqas"
    console.log(input);
  }
};

fetch("/")
  .then((res) => res.json())
  .then((json) => {
    console.log(json); // any
  });
```

Package to test:

```
{
  "name": "tsresettest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@total-typescript/ts-reset": "^0.3.7",
    "typescript": "^4.9.5"
  }
}
```

CodeSandbox: https://codesandbox.io/s/serene-mountain-rebrlv?file=/src/index.ts

**Comment by mattpocock** [comment]
You're using "module": "commonjs", in your tsconfig.json.

Probably worth a note about this in the readme.

**Comment by petetnt** [comment]
Yeah, that makes sense! Definitely worth it to document it to the README. Thanks for the answer!

**Comment by mattpocock** [comment]
Added to readme!

**Comment by toddheslin** [comment]
Also worth noting that `"moduleResolution": "node",` in the `tsconfig.json` also stops the individual imports from working. Want me to open a PR @mattpocock ?

**Comment by toddheslin** [comment]
Oh, for some more clarity - I found I couldn't actually update both `module` and `moduleResolution` in my project because of other bundling import issues. ie it would have required more refactoring that wasn't quite as easy.

Instead, I kept my `tsconfig.json` as it was and just imported individual features like this from the `dist` dir:

```ts
'@total-typescript/ts-reset/dist/json-parse'
```
