### ISSUE TITLE
make `isArray` more specific

### ISSUE THREAD

**Issue by smblee** [total-typescript/ts-reset#42]
I have a code:
```
  const path: string | string[];
  ...
  const paths = Array.isArray(path) ? path : [path];
```

With the new `isArray` assuming `unknown[]`, this breaks the type of `paths`.

Could we make the `isArray` more smart that it can infer the generic type?

**Comment by nikensss** [comment]
It seems like I got it, but I'm not very sure...
```
export interface ArrayConstructor {
  isArray<T>(arg: unknown): arg is T extends (infer K)[] ? K[] : T;
}

export function getValue(): string | string[] {
  return ['asdf'];
}

const main = async (): Promise<void> => {
  const p: string | string[] = getValue();
  const paths = Array.isArray(p) ? p : [p];
  console.log({ paths });
};

main()
  .then(() => console.log('Done!'))
  .catch(console.error);
```

When I check the type of `p` before and after the `:` in the ternary it indicates the proper types. But I don't know if I just built the perfect example to give me the types I want, haha!

**Comment by mattpocock** [comment]
I'm not seeing this break in the repo. I've added a test to cover it, and it's still not breaking.
