### ISSUE TITLE
Feature request - Smarter Object [keys,value,assign,...]

### ISSUE THREAD

**Issue by DavidWeiss2** [total-typescript/ts-reset#45]
Awesome Project!

I want to add type safety for all the Object static methods.

It's something that annoys me a lot. And I am capable of handling this.

Please let me know if I can start working on this.

**Comment by pnowak** [comment]
Hi @DavidWeiss2 
Look at this comment by @mattpocock about the same feature request  - https://github.com/total-typescript/ts-reset/issues/38#issuecomment-1438729718

So I think, the answer will be the same.
