### ISSUE TITLE
Support for hasOwn

### ISSUE THREAD

**Issue by bsitruk** [total-typescript/ts-reset#47]
Hi Matt,

First, thanks for this great initiative. **Keep rocking !**

**Small suggestion:** what about adding support for [Object.hasOwn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) ?

There's this [thread](https://github.com/microsoft/TypeScript/issues/44253) for reference.

**Comment by mattpocock** [comment]
This is a great idea, but I'd prefer to rely on the TS team's decision instead of attempting to jump the gun.
