### ISSUE TITLE
`['a','b'].join()` can return the type `'a,b'` instead of `string`

### ISSUE THREAD

**Issue by fregante** [total-typescript/ts-reset#58]
As described in the title. I’m not sure if it belongs to a reset, but it’s disappointing to call `join` a readonly-array and receive a bland `string`

Same goes for other array and string methods, I think these helpers already exist somewhere. 

I recently had an issue with this when using an advanced type that parses CSS selectors https://github.com/refined-github/refined-github/pull/6370#discussion_r1114234039

**Comment by mattpocock** [comment]
I don't think the juice is worth the squeeze on this one! It's quite a weighty addition and I don't think it's necessary in most cases.

**Comment by fregante** [comment]
Fair.

For future reference: https://solverfox.dev/writing/ts-typed-join/

**Comment by DeepDoge** [comment]
I think it might join the first 8 items only, then can add `${any}` at the end of it, if its any longer, so it doesn't go too deep.
But, I mean would I use it?
Maybe in some cases.
But when you combine strings literals with `+` operator, it also returns `string`, so maybe join returning strings makes more sense.

Either way, i tried it implement it like this (For future reference):

*array-join.d.ts*
```ts
/// <reference path="utils.d.ts" />

interface ReadonlyArray<T> {
  join<T extends readonly TSReset.Stringifyable[], S extends string = "">(
    this: T,
    seperator?: S
  ): TSReset.Join8<T, S>;
}
```
*utils.d.ts*
```ts
declare namespace TSReset {
// ...
  type Stringifyable = string | number | bigint | boolean | null | undefined;
  type Join8<T extends readonly Stringifyable[], S extends string> = T extends readonly [
    infer F extends T[0],
    ...infer R extends readonly Stringifyable[]
  ]
    ? `${F}${T["length"] extends 1
        ? ""
        : `${S}${R["length"] extends 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
            ? Join8<R, S>
            : `${Join8<readonly [R[0], R[1], R[2], R[3], R[4], R[5], R[6]], S>}${any}`}`}`
    : "";
```

And the tests:
```ts
import { doNotExecute, Equal, Expect } from "./utils";

doNotExecute(async () => {
  const arr = ["1", 2, 3n, true, false, null, undefined] as const;

  const str = arr.join(",");
  type tests = [Expect<Equal<typeof str, "1,2,3,true,false,null,undefined">>];
});

doNotExecute(async () => {
  const arr = ["1", 2] as const;

  const str = arr.join();
  type tests = [Expect<Equal<typeof str, "12">>];
});

doNotExecute(async () => {
  const arr = ["1", 2, 3n, true, false, null, undefined, {}] as const;

  const str = arr.join(",");
  type tests = [Expect<Equal<typeof str, string>>];
});

doNotExecute(async () => {
  const arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16] as const;

  // TL;DR case, Too deep
  const str = arr.join(",");
  type tests = [Expect<Equal<typeof str, `0,1,2,3,4,5,6,7${any}`>>];
});

doNotExecute(async () => {
  const arr = [] as const;

  const str = arr.join(",");
  type tests = [Expect<Equal<typeof str, "">>];
});
```

**Comment by fregante** [comment]
Looks great! I also realized it exists on type-fest as well 

https://github.com/sindresorhus/type-fest/blob/main/source/join.d.ts
