### ISSUE TITLE
Should potentially unsafe array accessing be handled?

### ISSUE THREAD

**Issue by KilianB** [total-typescript/ts-reset#61]
I am opening this issue more as a request for discussion not as an actual feature request as I am not sure if the use case really is worth the hassle of additional type guards. 

Currently you are able to access an arbitrary element in an array using either the bracket notation or the `at` function. In the below case typescript will still evaluate the elements to be of type number even though potentially they are undefined. 

````typescript
  const foo = [1,2,3];

  const bar = foo[5];  // undefined
  const baz = foo.at(-4);  // undefined
  const foobar = foo[2];  // number
````

This has been biting me multiple times in the past e.g. when using express-xml-bodyparser which implicitly turns children into arrays. 
I just feel like arrays usually are accessed in forEach, map or loops with the length fields as limits so that it isn't an issue for 98% of the time and having to introduce additional type guards everywhere might be to much of a drawback.

What do you think? Is it even possible to override the typing of the array getter?

**Comment by mattpocock** [comment]
The config option `noUncheckedIndexedAccess` is enough to cover this case, I think - with the possible exception of `foo.at`
