### ISSUE TITLE
Implementation in a monorepo with frontend and backend apps

### ISSUE THREAD

**Issue by benpsnyder** [total-typescript/ts-reset#62]
@mattpocock kindly provide feedback on nrwl/nx#15196 regarding monorepo implementation with front-end and backend TS apps

Nice work! Thank you!

**Comment by nicholasgriffintn** [comment]
Best way is probably to create a shared tsconfig and then use extends:

https://www.typescriptlang.org/tsconfig#extends

**Comment by mattpocock** [comment]
Closing as duplicate of #24

**Comment by nicholasgriffintn** [comment]
> Best way is probably to create a shared tsconfig and then use extends:
> 
> https://www.typescriptlang.org/tsconfig#extends

Ahh I see that's not a thing now, was wondering this myself. What I've done is just make a .d.ts file at the root and then include that in the individual tsconfigs. Seems to work.
