### ISSUE TITLE
Bug: library can't be installed as a dev dependency

### ISSUE THREAD

**Issue by therosbif** [total-typescript/ts-reset#71]
Is there any way to make this lib not need to be a runtime dependency? Since it's only affecting typescript, shouldn't it be ok as a dev dependency?

`pnpm prune --prod`

```
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '@total-typescript/ts-reset'
```

**Comment by mondash** [comment]
How are you including this in your project? If you're using a separate `.d.ts` file, depending on your build tool, you should be able to exclude that file from your dist so there's no references to that import.

**Comment by therosbif** [comment]
Yes! Sorry this works, I created the issue when the README still recommended importing the lib in any ts file
