### ISSUE TITLE
Rename package to `ts-reset`

### ISSUE THREAD

**Issue by nickmccurdy** [total-typescript/ts-reset#8]
Short package names make installing and finding packages easier. There is already a [`ts-reset`](https://www.npmjs.com/package/ts-reset) package, but it has few downloads and does not do anything, so you can use the [dispute resolution policy](https://docs.npmjs.com/policies/disputes) to request it. If they ask for an explanation, tell them the package owner is squatting your project's name.

**Comment by mattpocock** [comment]
I agree - but it's also extremely recently published, which indicates that it's still active. If they're feeling generous I'd be happy to take it.

**Comment by peschee** [comment]
@mattpocock that `ts-reset` package is empty, it has no reference to a GitHub repo and has been created very recently—coincidence? It seems strange, but maybe the author reserved the name and is planning something more.

**Comment by danreeves** [comment]
https://www.npmjs.com/package/ts-reset has a deprecation notice pointing to this package. I assume they'd be open to giving up the name
