### ISSUE TITLE
reduce needs reset when used with as-const 

### ISSUE THREAD

**Issue by prophet1996** [total-typescript/ts-reset#81]
https://www.typescriptlang.org/play?ts=5.0.0-dev.20230224#code/LAKAxg9gdgzgLgAgIYCcUILwINoEYA0ATPgMz4As+ArPgGwC6CyMCkscooANgKaIo8AJgFcwPTMjQA6ASLEAKeUjBh8ANyRdhPAJQYAfAG9QTAPSnW0GBF5SuEAObyNW3SYQC4wlFGQqA1C7aoAC+OpwgQA

**Comment by mattpocock** [comment]
Is there a practical case where this is useful? This one feels very abstract.

**Comment by m10rten** [comment]
I see your point, `number is not assignable to 1 | 2 | 3 | 4 | 5 | 6`, this is fixable by adding a type to the callback.
I do not see a need to reset its default number property.

**Comment by guillaumebrunerie** [comment]
You can instead write
```typescript
let reduce = arr.reduce<number>((acc,value)=>{
  // console.log(value)
  return acc+value
}, 0)
```

**Comment by prophet1996** [comment]
> y adding a type to the callback.
> I do not see a need to reset its default number property.

tried this 
https://www.typescriptlang.org/play?ts=5.0.0-dev.20230224#code/LAKAxg9gdgzgLgAgIYCcUILwINoEYA0ATPgMz4As+ArPgGwC6CyMCkscooANgKaIo8AJgFcwPTMjQA6ASLEAeKMIC2AIx4oAfAAptSMGHwA3JF2E8AlBk0BvUEwFxhKKMgMBqE2Z6gAvhc4QIA

now it doesn;t understand that without passing the second argument, the first item becomes the second argument,

**Comment by mattpocock** [comment]
I'm still not seeing a practical use case here, so keeping the issue closed.

**Comment by guillaumebrunerie** [comment]
> now it doesn;t understand that without passing the second argument, the first item becomes the second argument,

Not passing a second argument seems weird to me, as it will throw an exception if the array happens to be empty. Do you have any concrete example where it is difficult to figure out what the initial value is supposed to be?
