### ISSUE TITLE
[Feature request] - Add better support for `Array.prototype.at()`

### ISSUE THREAD

**Issue by petervmeijgaard** [total-typescript/ts-reset#84]
Hi Matt! Yet again, thanks for this library! I've got a feature request regarding the `Array.prototype.at()` function.

I'm currently struggling with the way `Array.prototype.at()` is being handled in TypeScript. In my opinion, it can be a bit smarter than it currently is set up.

Given the following example:

```typescript
type Item = {
    title: string;
}

const logItem = (item: Item) => console.log(item);

const logLastItem = (items: Item[]) => {
    if (!items.at(-1)) {
        return;
    }

    // Gives a type error, but I expect this to work
    // => Type 'undefined' is not assignable to type 'Item'.
    return logItem(items.at(-1));
};

const logFirstItem = (items: Item[]) => {
    if (!items.at(0)) {
        return;
    }

    // Gives a type error, but I expect this to work
    // => Type 'undefined' is not assignable to type 'Item'.
    return logItem(items.at(0));
};
``` 

I would expect that this gets parsed as valid TypeScript code due to the check prior to the call to `logItem`.

Do you agree or am I missing something here?

---

[TypeScript Playground link](https://www.typescriptlang.org/play?target=9&ts=4.6.1-rc#code/C4TwDgpgBAksEFsoF4oG8CwAoKurAEtgAbCALigGdgAnAgOwHMBubAX22wGMB7e6qMR6M4iFFAAURRBVEIAlCgB8UXvx6kAdEMZT4C1lm58BOgDIBDanPF7ElWfoDaAXUXIVmHHgIAzSQCE0giUmhbAEgC0AIzyil54iVA0EMAArjT0hokcRt64KemZgsJydiFhETFxhmyGxvzAJYwAYgQ01vq2wQ6wzm7K6NiJfoE9lRIADHFD+UmFGVnDeLnLBamLzWXj4VM17IZAA)

**Comment by petervmeijgaard** [comment]
The same can be said for the following example:

```typescript
type Item = {
    title: string;
}

const logItem = (item: Item) => console.log(item);

const logLastItem = (items: Item[]) => {
    if (items.length === 0) {
        return;
    }

    // Gives a type error, but I expect this to work
    // => Type 'undefined' is not assignable to type 'Item'.
    return logItem(items.at(-1));
};
```

Due to the previous check, we make sure that the array has items.

[TypeScript Playground link](https://www.typescriptlang.org/play?target=99#code/C4TwDgpgBAksEFsoF4oG8CwAoKurAEtgAbCALigGdgAnAgOwHMBubAX22wGMB7e6qMR6M4iFFAAURRBVEIAlCgB8UXvx6kAdEMZT4C1lm58BOgDIBDanPF7ElWfoDaAXUXIVmHHgIAzSdIIlNoQTMAAFijIqAAMil54iVA0EMAArjT02IkcRt64APQFUADiBABuEJRQFvjg0BA0NDw0ADRQAEZpwLBQEAAekFw9EQTVwDxQAO4tANbZeEXKUAAq9VAA5Gn0ACYQvgwQOxtQY1D0PD1WlASM9BYdpPiToJCbchuaC7gp6ZmCwjkdiCmgswAkAFoAIzyeSGNiGIA)
---

**Comment by mattpocock** [comment]
I think you should move this to the TS repo itself, we won't be able to handle logic like this in ts-reset.
