### ISSUE TITLE
Change Body.json() to return unknown instead of any

### ISSUE THREAD

**Issue by sandstromdev** [total-typescript/ts-reset#87]
Reading json from a Response object returns any.

```ts

const response = await fetch('...');
const data = await response.json();
//    ^?   const data: any

```

```ts
declare global {
  interface Body {
    json(): Promise<unknown>;
  }
}
```

**Comment by mattpocock** [comment]
Is this in a React Native app?

**Comment by sandstromdev** [comment]
No, it's a SvelteKit app, so just the normal Fetch API.

**Comment by mattpocock** [comment]
So the existing `ts-reset/fetch` doesn't work on this?

**Comment by sandstromdev** [comment]
Turns out it was an issue with another package modifying the interface, so no issue on your part. Removing the conflicting package solved it.

Thanks for the awesome library!
