### ISSUE TITLE
Problem/conflict with `PartialDeep` from `type-fest`

### ISSUE THREAD

**Issue by joealden** [total-typescript/ts-reset#88]
When enabling `ts-reset`, the behaviour of [`PartialDeep`](https://github.com/sindresorhus/type-fest/blob/main/source/partial-deep.d.ts) breaks.

Example:

```ts
import "@total-typescript/ts-reset";

import { PartialDeep } from "type-fest";

type Test1 = {a?: { a1: Array<string> } }

type Test2 = PartialDeep<Test1>;

const test: Test2 = {a: { a1: [""] }};
```

https://www.typescriptlang.org/play?#code/PTAEEsFsAcHsCcAuoBEABRtEEMA2BaRAT2gFMBnAY3nGkWEXP3gtMRQG5QRQBVAO0qxIkUv2SZQ5UqVCl48BKHygWQkWMTh+Ac1AB3WPwDkyFgDd5iADSrSAMxbkAFhH7lEpbABMAdACh-KDgkUABvUAAFbCRwPAARGWhQAF9QR2FUYjJ8ewp2DkDs2QAVfIBGUABecOwAfgAucNBscqaAQQVsIgAeDxpdAD5U1KKSUvyAJmqomK0EpJ6yj3LBwv8hdwl8puXEaZqw7CaI1qaAbRQUAF1UlMLQR6fnl9fHngA9OqA.

**Comment by joealden** [comment]
It looks like this is no longer a problem (something either changed in `ts-reset` or `type-fest` I presume), so closing!

**Comment by mattpocock** [comment]
Phew!
