### ISSUE TITLE
Missing some falsy value/type

### ISSUE THREAD

**Issue by pnowak** [total-typescript/ts-reset#9]
I wonder why the NonFalsy type (https://github.com/total-typescript/ts-reset/blob/main/src/entrypoints/utils.d.ts#L2) lacks the BigInt zero (`0n`) and `NaN` - https://developer.mozilla.org/en-US/docs/Glossary/Falsy. 

Maybe it is because it's a rare situation to have used BigInt, isn't it?

**Comment by mattpocock** [comment]
Good catch! `NaN` is not available as a literal in TS, but `0n` is. Deployed a fix for this.
