### ISSUE TITLE
Mention JSDoc (+ checkJs  + VSCode)

### ISSUE THREAD

**Issue by myfonj** [total-typescript/ts-reset#93]
I think no-build vanilla JS VSCode `// @ts-check`  / `js/ts.implicitProjectConfig.checkJs` could benefit from this project and perhaps it would be worth mentioning it in the readme. Something like 

```JavaScript
/// <reference path="../ts-reset-0.3.7/src/entrypoints/recommended.d.ts"/>
```
for "I've just unpacked zip from [releases](https://github.com/total-typescript/ts-reset/releases)" scenario, or

```JavaScript
/// <reference path="../node_modules/@total-typescript/ts-reset/dist/recommended.d.ts"/>
```
for "I've did the NPM install" scenario could probably be enough to nod no-build-step audience towards this goodness.

----

BTW [NPM dist folder of 0.3.7](https://www.npmjs.com/package/@total-typescript/ts-reset/v/0.3.7?activeTab=explore) contains bunch of empty files (.js, .mjs). Is it OK?

**Comment by mattpocock** [comment]
Could you leave these instructions in Discussions? I think this use case is niche enough that I'd like it to be archived there, not part of the docs themselves.

**Comment by myfonj** [comment]
Not completely sure what "Discussions" with capital "D" here in closed completed issue refers to, so assuming "random discussions on the interwebs mentioning this project" with lowercase "d". So I've complied and left [one such comment on HN](https://news.ycombinator.com/item?id=35009194).

**Comment by mattpocock** [comment]
My bad! I hadn't activated it yet:

https://github.com/total-typescript/ts-reset/discussions
