### ISSUE TITLE
Document how the Equal<> assertion works?

### ISSUE THREAD

**Issue by maxpblum** [total-typescript/ts-reset#94]
Thanks for the cool library! I am confused reading the Equal test assertion, which seems to check equality of two types by using sort of synthetic anonymous function types. Can you add some comments explaining how this actually manages to check equality? Very neat idea. Impressive if you came up with it, and it came from a website can you have a link? Thanks!

**Comment by mattpocock** [comment]
Hey! No I didn't, it's a popular idea. I'll write an article at some point but I won't do it in this repo.
