### ISSUE TITLE
filterBoolean tests seem to be failing?

### ISSUE THREAD

**Issue by maxpblum** [total-typescript/ts-reset#98]
See [this TypeScript playground example](https://www.typescriptlang.org/play?#code/C4TwDgpgBAcg9gOwGIEMA2BnEAeAKgPigF4pcoIAPYCBAEwygDN0NoAfKABig4CJeeUBAFc0aQcLoRGASwQRagzggBQUdVAD8QiADcIAJzUaAXKQDcKlXOoHmAY2gBBAwZQ4CUAN7HZaWwAUYAYKMvYo1GYAQnBwaBAoCADCiBjABsL2wHAGADRQwAAWMhguAOaaZokgAJRm8MgsHvgA2gC6lgC+VqCQUACiFJBZeORUNPQFGRCEJLiWvdD9AI7C6NgAGvkAmrNQAXj4ATXEhGSU1HQMG1pQAIxQZgBMJxcTDNjGuLkqRydEZzGl0m21uD2exm06WEEGMZmYmAglnsqWAUFocHgwEGEHswmoxH2jEk9jMx1OUGq-0IXk6lhUGKxOLx1AC5IB3mMKIQaUprkJLTu+Se+QAzPlJLRpHIFB0rOpubyQhhRGiSChXAA6PyBGJxBIIGr09SLAoQNIMEgtQbDYDYFZrNDYRZwRhQZWq-IiAC2ACNDO18Pg5Z0jVZGXBsRRcfiIGzqZyFai+QYBbw7rx8rwnpmoJLpfJaG1KQxFcBjVAy+7zarCRqDNqZP5DAE9fFEmHjKbqBaBTbcXaHesXW6Pf58gF0wI+DmaoHg11OxGozHWeyaVzk-WBZwvaI0BKpLJC-kEaws7xiyhS6iK1Wx2qU43mwZW7F24aK93zcBLVBrUMA72qsw7gBArrViq446PoBjziGS6YpGzKxvGFI+EmPJovWZLcBwIhiBIR4yooHBnuwUD8EohrtAKxjqLu9FCPuPwaHmxEnkx5GsRo-A8QxCA8XKm5YZBtbqlqOotm2BqdiaYFmr2Vr9iMQ5OiOYnQfIsHwYu5hAA). Perhaps something changed in a recent version of TypeScript such that this no longer works?

**Comment by mondash** [comment]
You're missing the augment for readonly arrays.

https://github.com/total-typescript/ts-reset/blob/37dc8f0af0b8aa055ec1c740c83a45ccf3d34cf7/src/entrypoints/filter-boolean.d.ts#L7-L9

**Comment by mattpocock** [comment]
Thanks @mondash!
