### ISSUE TITLE
Doesn't work with certain tsconfig.json options

### ISSUE THREAD

**Issue by GRA0007** [total-typescript/ts-reset#99]
We have a large project that relies on some old JavaScript files that are yet to be converted to TypeScript. So that we can get typechecking in the TS areas, we have `allowJs` set to `true` in the tsconfig. Unfortunately this seems to break subclassing builtins like `Array<T>`. As a result, importing any parts of this library do not work.

**Comment by mattpocock** [comment]
@GRA0007 Could you provide a repro? Keen to get to the bottom of this

**Comment by GRA0007** [comment]
Sure @mattpocock, here is a sandbox replicating the issue: https://codesandbox.io/s/ts-reset-with-allowjs-7h8bgc
As you can see it doesn't even require any JS files to be involved. Also, I think the config option `module: 'ES2022'` might have something to do with it as well.

**Comment by mondash** [comment]
Interestingly enough, when I add `"moduleResolution": "node"` to `tsconfig.json`, even with `"allowJs": true` this works 🤔

**Comment by mattpocock** [comment]
@mondash You're right! That tsconfig.json file looks pretty sparse and is missing a couple of key options @GRA0007. It's also erroring with a weird error. Is this the exact tsconfig file you're using in your project?

**Comment by mondash** [comment]
@mattpocock I suspect the "weird error" on the tsconfig is due to TS attempting to transpile the JS file `test.js` (because of `"allowJs": true`) and failing due to a naming collision. TS would typically transpile `test.ts` into `test.js` in the same directory (which is the default behavior when `"outDir"` isn't specified, but maybe becuase it's already a `.js` file it's getting confused. 🤷

I'd recommend specifying an outDir pretty much all the time so idk how problematic this issue really is.

**Comment by mattpocock** [comment]
I've changed the title of this issue to represent that we don't really know what's going on here, and added the help wanted tag in case someone wants to investigate.

**Comment by GRA0007** [comment]
> @mondash You're right! That tsconfig.json file looks pretty sparse and is missing a couple of key options @GRA0007. It's also erroring with a weird error. Is this the exact tsconfig file you're using in your project?

It's not, this is what we're using exactly:
```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "strict": true,
    "paths": {
      "/*": ["./*"]
    },
    "baseUrl": "./",
    "noEmit": true,
    "esModuleInterop": true,
    "allowJs": true,
    "skipLibCheck": true,
    "module": "ES2022",
    "moduleResolution": "node",
    "types": ["node", "vite/client", "vite-plugin-pwa/client"]
  },
  "exclude": [
    "**/node_modules/*",
    "**/dist/*",
    "**/.git/*",
  ],
}
```

As for the `test.js` in the sandbox, I deleted that but apparently it came back 😂, even with it gone the issue persists.

You're right that adding `"moduleResolution": "node"` fixes the issue in the sandbox, however we have that in our actual config above so maybe another option is causing this.

**Comment by mondash** [comment]
@GRA0007 I think the missing config option is `outDir`. Are you actually generating files via this config, or is it just used for typing information?

If you're generating files from this, I'd _highly_ recommend specifying an `outDir` (such as `"outDir": "./dist"`), so your built assets can be isolated from source code (don't forget to update your `"main"` property in `package.json` etc). If you're just using `tsconfig.json` for type information, `"noEmit": true` might work, though I'd still recommend specifying an `outDir` (such as `"outDir": "./build"`) even if those files never get generated (could potentially assist in debug as well).

**Comment by GRA0007** [comment]
We're just using it for typing, it's not a library so we don't need to generate any types. I can add an outDir but it should have no effect with `noEmit` set to true.

**Comment by mondash** [comment]
@GRA0007 Even with just using for type-checking, I suspect that conflicts when generating `.js` files into files with the same name and extention are preventing TS from properly parsing your project. By configuring an `outDir` (even if no files are actually generated), that should prevent any naming collisions.
